# Generated by Django 5.1.8 on 2025-08-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0004_alter_vehicle_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='coments',
            field=models.TextField(blank=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('BYD', 'BYD'), ('Changan', 'Changan'), ('Chery', 'Chery'), ('Chevrolet', 'Chevrolet'), ('Citroen', 'Citroen'), ('DFSK', 'DFSK'), ('Dodge', 'Dodge'), ('Faw', 'Faw'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Geely', 'Geely'), ('Haima', 'Haima'), ('Haval', 'Haval'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Jeep', 'Jeep'), ('Jetour', 'Jetour'), ('JMC', 'JMC'), ('Kia', 'Kia'), ('Land Rover', 'Land Rover'), ('Mazda', 'Mazda'), ('Mercedes Benz', 'Mercedes Benz'), ('Mitsubishi', 'Mitsubishi'), ('Nizzan', 'Nizzan'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Seat', 'Seat'), ('Subaru', 'Subaru'), ('Toyota', 'Toyota'), ('Volvo', 'Volvo'), ('VW', 'VW'), ('Zuzuki', 'Zuzuki')], max_length=50, verbose_name='Marca'),
        ),
    ]
