# Generated by Django 6.0.7 on 2026-07-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0005_alter_service_coments_alter_vehicle_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('Filtro de aire', 'Filtro de aire'), ('Filtro de aceite', 'Filtro de aceite'), ('Cambio aceite', 'Cambio aceite'), ('Cambio pastillas de freno', 'Cambio pastillas de freno'), ('Filtro de combustible', 'Filtro de combustible'), ('Cambio de lubricación de transmisión', 'Cambio de lubricación de transmisión'), ('Cambio Correa de Distribución ', 'Cambio Correa de Distribución'), ('Cambio de amortiguadores', 'Cambio de amortiguadores'), ('Cambio de cubiertas', 'Cambio de cubiertas'), ('Cambio de batería', 'Cambio de batería'), ('Carga Combustible', 'Carga Combustible'), ('Chapista', 'Chapista'), ('Tren delantero', 'Tren delantero'), ('Electricidad', 'Electricidad'), ('Carga Nafta', 'Carga Nafta'), ('Pinchadura', 'Pinchadura'), ('Me hizo un ruido', 'Me hizo un ruido'), ('Cualquier otra cosa', 'Cualquier otra cosa')], max_length=500, verbose_name='Tipo de Servicio'),
        ),
    ]
